CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DROP TABLE AppUser;
CREATE TABLE AppUser (
  id UUID NOT NULL DEFAULT uuid_generate_v4(),
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
